from __future__ import annotations

from typing import Any, Protocol

from knowledge_agent_mcp.models.knowledge_item import KnowledgeItem


class KnowledgeRepository(Protocol):
    def create_schema(self) -> None: ...

    def upsert_item(
        self,
        item: KnowledgeItem,
        resolved_path: str,
        content_hash: str,
        file_mtime: float,
        file_size: int,
    ) -> None: ...

    def delete_item(self, knowledge_id: str) -> None: ...

    def load_item_by_id(self, knowledge_id: str) -> KnowledgeItem: ...

    def relations_for(self, knowledge_id: str) -> list[dict[str, str]]: ...

    def source_stub(self, knowledge_id: str) -> dict[str, Any]: ...

    def all_items(self) -> list[KnowledgeItem]: ...

    def items_by_ids(self, knowledge_ids: list[str]) -> list[KnowledgeItem]: ...

    def search_ids(self, query: str, limit: int = 100) -> list[str]: ...

    def get_indexed_paths(self) -> dict[str, dict[str, Any]]: ...

    def update_index_metadata(self, key: str, value: str) -> None: ...

    def commit(self) -> None: ...
